# Generated by Django 4.1.1 on 2022-09-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_wallet', '0003_account_title_alter_receipt_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
