# Generated by Django 4.1.1 on 2022-09-30 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_wallet', '0004_receiptexcel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReceiptExcel',
        ),
    ]
