# Generated by Django 4.1.1 on 2022-10-03 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_wallet', '0008_receipt_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='user',
        ),
    ]
